package visao;

import dao.cliente.ClienteDAO;
import dao.cliente.ClienteDAOMySQL;
import modelo.Cliente;

public class FrmCadastroCliente extends javax.swing.JFrame {

    public FrmCadastroCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jTFEndereco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTFCidade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFEstado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTFEscolaridade = new javax.swing.JTextField();
        JBTSair = new javax.swing.JButton();
        JBTLimpar = new javax.swing.JButton();
        jBTSalvar = new javax.swing.JButton();
        jBTExcluir = new javax.swing.JButton();
        JBTAlterar = new javax.swing.JButton();
        JBTListar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTFCEP = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Dados de Cliente");

        jLabel2.setText("Nome:");

        jTFNome.setName("JTFNome"); // NOI18N

        jTFEndereco.setName("JTFNome"); // NOI18N

        jLabel3.setText("Endereço:");

        jLabel4.setText("Cidade:");

        jTFCidade.setName("JTFNome"); // NOI18N

        jLabel5.setText("Estado:");

        jTFEstado.setName("JTFNome"); // NOI18N

        jLabel6.setText("CEP:");

        jTFEscolaridade.setName("JTFNome"); // NOI18N

        JBTSair.setText("Sair");
        JBTSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTSairActionPerformed(evt);
            }
        });

        JBTLimpar.setText("Limpar");
        JBTLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTLimparActionPerformed(evt);
            }
        });

        jBTSalvar.setText("Salvar");
        jBTSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTSalvarActionPerformed(evt);
            }
        });

        jBTExcluir.setText("Excluir");
        jBTExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTExcluirActionPerformed(evt);
            }
        });

        JBTAlterar.setText("Alterar");
        JBTAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTAlterarActionPerformed(evt);
            }
        });

        JBTListar.setText("Listar");
        JBTListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTListarActionPerformed(evt);
            }
        });

        jLabel7.setText("Escolaridade:");

        jTFCEP.setName("JTFNome"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jTFCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JBTAlterar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBTListar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JBTLimpar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBTSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBTSalvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBTExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jTFCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {JBTAlterar, JBTLimpar, JBTListar, JBTSair, jBTExcluir, jBTSalvar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jBTSalvar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBTListar)
                        .addGap(5, 5, 5))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JBTAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBTExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBTLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBTSair))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(3, 3, 3)
                        .addComponent(jTFEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(1, 1, 1)
                        .addComponent(jTFCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBTSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JBTSairActionPerformed

    private void JBTLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTLimparActionPerformed
        jTFCidade.setText("");
        jTFEndereco.setText("");
        jTFEscolaridade.setText("");
        jTFEstado.setText("");
        jTFCEP.setText("");
        jTFNome.setText("");
    }//GEN-LAST:event_JBTLimparActionPerformed

    private void jBTSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTSalvarActionPerformed
        if (!jTFNome.getText().equals("")) {
            Cliente cliente = new Cliente();
            if (clienteId != -1) {
                cliente.setClienteId(clienteId);
            }
            cliente.setNome(jTFNome.getText());
            cliente.setEndereco(jTFEndereco.getText());
            cliente.setCidade(jTFCidade.getText());
            cliente.setEstado(jTFEstado.getText());
            cliente.setCep(jTFCEP.getText());
            cliente.setEscolaridade(jTFEscolaridade.getText());

            ClienteDAO clientedao = new ClienteDAOMySQL();
            if (clientedao.salvar(cliente)) {
                javax.swing.JOptionPane.showMessageDialog(null, "Cliente cadastrado com suscesso!");
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "Cliente não cadastrado!");
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "O Nome deve ser preenchido!");
            jTFNome.requestFocus();
        }
    }//GEN-LAST:event_jBTSalvarActionPerformed

    private void JBTListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTListarActionPerformed
        //this.setVisible(false);
        new FrmClienteListar().setVisible(true);
    }//GEN-LAST:event_JBTListarActionPerformed

    private void jBTExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTExcluirActionPerformed
        String id = javax.swing.JOptionPane.showInputDialog("Digite o id a ser excluído");
        ClienteDAO clientedao = new ClienteDAOMySQL();
        Cliente cliente = clientedao.consultarPK(id);
        if (cliente != null) {
            jTFNome.setText(cliente.getNome());
            jTFEndereco.setText(cliente.getEndereco());
            jTFCidade.setText(cliente.getCidade());
            jTFEstado.setText(cliente.getEstado());
            jTFCEP.setText(cliente.getCep());
            jTFEscolaridade.setText(cliente.getEscolaridade());
            Object[] opcoes = {"Sim", "Não"};
            int resposta = javax.swing.JOptionPane.showOptionDialog(null, "Confirma a exclusão do Cliente?", "Exclusão", 0, javax.swing.JOptionPane.QUESTION_MESSAGE, null, opcoes, opcoes[1]);
            if (resposta == 0) {
                if (clientedao.apagarPK(Integer.parseInt(id))) {
                    javax.swing.JOptionPane.showMessageDialog(null, "Cliente excluído com suscesso!");
                    jTFCidade.setText("");
                    jTFEndereco.setText("");
                    jTFEscolaridade.setText("");
                    jTFEstado.setText("");
                    jTFCEP.setText("");
                    jTFNome.setText("");
                } else {
                    javax.swing.JOptionPane.showMessageDialog(null, "Cliente não excluído!");
                }
            }
        }
    }//GEN-LAST:event_jBTExcluirActionPerformed

    private void JBTAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTAlterarActionPerformed
        String id = javax.swing.JOptionPane.showInputDialog("Digite o id a ser alterado");
        ClienteDAO clientedao = new ClienteDAOMySQL();
        Cliente cliente = clientedao.consultarPK(id);
        if (cliente != null) {
            clienteId = cliente.getClienteId();
            jTFNome.setText(cliente.getNome());
            jTFEndereco.setText(cliente.getEndereco());
            jTFCidade.setText(cliente.getCidade());
            jTFEstado.setText(cliente.getEstado());
            jTFCEP.setText(cliente.getCep());
            jTFEscolaridade.setText(cliente.getEscolaridade());
        }
    }//GEN-LAST:event_JBTAlterarActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCadastroCliente().setVisible(true);
            }
        });
    }
    private int clienteId = -1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTAlterar;
    private javax.swing.JButton JBTLimpar;
    private javax.swing.JButton JBTListar;
    private javax.swing.JButton JBTSair;
    private javax.swing.JButton jBTExcluir;
    private javax.swing.JButton jBTSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTFCEP;
    private javax.swing.JTextField jTFCidade;
    private javax.swing.JTextField jTFEndereco;
    private javax.swing.JTextField jTFEscolaridade;
    private javax.swing.JTextField jTFEstado;
    private javax.swing.JTextField jTFNome;
    // End of variables declaration//GEN-END:variables
}
